name: Publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh  # Maven settings server id
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Test
        run: mvn clean test
        
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Create settings.xml
        run: |
            cat <<EOF > ./settings.xml
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
        
                <servers>
                    <server>
                        <id>ossrh</id>
                        <username>${{ secrets.OSSRH_USERNAME }}</username>
                        <password>${{ secrets.OSSRH_PASSWORD }}</password>
                    </server>
                </servers>
        
                <profiles>
                    <profile>
                        <id>release</id>
                        <properties>
                            <gpg.executable>gpg</gpg.executable>
                            <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
                        </properties>
                    </profile>
                </profiles>
        
                <activeProfiles>
                    <activeProfile>release</activeProfile>
                </activeProfiles>
            </settings>
            EOF

      - name: Build and Publish
        run: mvn clean deploy -P release -s ./settings.xml